### ISSUE TITLE
v0.1.0 TODO

### ISSUE THREAD

**Issue by LonelySteve** [LonelySteve/QQbotBaiduWikiPlugin#4]
- [ ] 解耦 baidu_wiki.py 脚本：
      - \_\_init\_\_.py —— 用于定义 QQbot 的回调函数
      - config.py —— 用于管理配置（包括 QQbot 配置及独立的配置）
      - info.py —— 通过网络请求中获取信息（百度百科热搜词条，百度百科历史上的今天，天气预报等信息）
      - template.py —— 提供管理 Jinja2 模板的方法，过滤器等
      - exceptions.py —— 定义本插件的异常类
      - logger.py —— 日志器，继承于QQbot
- [ ] 预增加配置系统，独立于 QQbot。序列化储存脚本运行状态，TO FIX #3 
- [x] 主推服务器运行分支，保留旧分支为 old_branch
      -  移除一些无用配置：
            - on_exit_show_the_message
            - exit_with_copy_the_message
